#!/bin/sh -e

. ci/travis/lib.sh

handle_default() {
	mkdir -p build
	cd build
	cmake -DCMAKE_CXX_FLAGS="-std=c++11" ..
	make
	cd ..
}

handle_centos() {
	handle_default
}

handle_centos_docker() {
        run_docker_script inside_docker.sh \
                "centos:centos${OS_VERSION}" "centos"
}

handle_ubuntu_docker() {
        run_docker_script inside_docker.sh \
                "ubuntu:${OS_VERSION}"
}

OS_TYPE=${OS_TYPE:-default}

handle_${OS_TYPE}
